# Generated by Django 4.2.5 on 2023-09-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='Category_name',
            new_name='category_name',
        ),
    ]
