# Generated by Django 4.2.5 on 2023-09-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_category_name_categorymodel_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditemmodel',
            old_name='Category',
            new_name='category',
        ),
    ]
