# Generated by Django 4.2.5 on 2023-09-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_category_fooditemmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='menu.categorymodel'),
        ),
    ]
