# Generated by Django 4.2.5 on 2023-09-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'resturant'), (2, 'customer')], null=True),
        ),
    ]
