# Generated by Django 4.2.5 on 2023-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
