# Generated by Django 4.2.5 on 2023-10-01 19:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofilemodel_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
