# Generated by Django 4.2.5 on 2023-10-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('pay', 'Pay')], max_length=100),
        ),
    ]
