# Generated by Django 4.2.5 on 2023-10-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0005_alter_openinghourmodel_options_and_more'),
        ('orders', '0003_alter_paymentmodel_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendormodel'),
        ),
    ]
